### ISSUE TITLE
[web3] Update MARKET types using Typechain to support web3 v1

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/types#33]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a developer, I need MARKET types to support web3 v1 so I can use web3 in our projects.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
We want to use web3 v1.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Current Behavior
[comment]: # (Describe what actually happened.)
Support of web3 0.20.x types

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Support of web3 v1 types 

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Now that Typechain supports web3 v1, upgrade our types to use web3 v1

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
- All MARKET types converted so we can use web3 v1 in `MARKET.js` and the dApp.
- Create or modify the tests.
- All tests pass.

**Comment by eswarasai** [comment]
Below are the required changes to upgrade to `web3@1.0.0`

`@types` --
1) Update all the tests to work with latest typings
2) Figure out required dependencies to be installed in order to get the installed types working in the published package

`@marketjs` --
1) Fix all the type errors due to latest typings update
2) Validate the functionality isn't broken due to updated code by fixing the tests

**Comment by eswarasai** [comment]
Removing the test framework from the `types`

cc: @MARKETProtocol/core
